# Generated by Django 6.0.3 on 2026-03-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gregorian_date', models.DateField(unique=True)),
                ('gregorian_year', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('gregorian_month', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('gregorian_day', models.PositiveSmallIntegerField(editable=False)),
                ('hijri_year', models.PositiveSmallIntegerField(db_index=True)),
                ('hijri_month', models.PositiveSmallIntegerField(db_index=True)),
                ('hijri_day', models.PositiveSmallIntegerField()),
                ('weekday', models.CharField(editable=False, max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('gregorian_date',),
                'constraints': [models.UniqueConstraint(fields=('hijri_year', 'hijri_month', 'hijri_day'), name='unique_hijri_date')],
            },
        ),
    ]
